name: flake8

on:
  - push
  - pull_request


jobs:
  tools:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install flake8
      - name: Run flake8
        run: flake8 --append-config pyproject.toml wslpath
